#!/bin/bash  
# Call this with multiple arguments  
# for example : ls *.{ogv,OGV} | xargs to_avi  
N=$#;  
echo "Converting $N files !"  
for ((i=0; i<=(N-1); i++))  
do  
echo "converting" $1  
filename=${1%.*}  
mencoder "$1" -ovc xvid -xvidencopts pass=1 -oac mp3lame -o $filename.avi  
shift 1  
done  
