#!/bin/bash  
# ogv2mp3  
# Call this with multiple arguments  
# for example : ls *.{ogv,OGV} | xargs ogv2mp3  
N=$#;  
echo "Converting $N files !"  
for ((i=0; i<=(N-1); i++))  
do  
echo "converting" $1  
filename=${1%.*}  
mencoder "$1"  -oac mp3lame -ovc copy -of rawaudio -o $filename.mp3  
shift 1  
done  
